name: Build Wretch

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  NIGHTLY_BUILD: 1

permissions:
  contents: write
  id-token: write
  pull-requests: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
        
        - name: macOS
          os: macos-latest
        
        - name: Linux
          os: ubuntu-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Cache Cargo Registry and Builds
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Lint
      run: cargo clippy --verbose

    - name: Build
      run: |
        cargo build --verbose
        cargo build --release --verbose

    - name: Run tests
      run: |
        cargo test --verbose
        cargo test --release --verbose

    - name: Test Binary
      shell: bash
      run: |
        if [[ ${{ matrix.config.os }} == 'windows-latest' ]]; then
          echo "Testing Debug Binary"
          target/debug/wretch.exe
          echo "Testing Release Binary"
          target/release/wretch.exe
        else
          echo "Testing Debug Binary"
          chmod +x target/debug/wretch
          target/debug/wretch
          echo "Testing Release Binary"
          chmod +x target/release/wretch
          target/release/wretch
        fi
      env:
        CLICOLOR_FORCE: 1

    - name: Change File Names
      shell: bash
      id: rename
      run: |
        if [[ ${{ matrix.config.os }} == 'windows-latest' ]]; then
          echo "debugfilename=wretch-debug-nightly.exe" >> $GITHUB_OUTPUT
          echo "releasefilename=wretch-release-nightly.exe" >> $GITHUB_OUTPUT
          mv target/debug/wretch.exe target/debug/wretch-debug-nightly.exe
          mv target/release/wretch.exe target/release/wretch-release-nightly.exe
        elif [[ ${{ matrix.config.os }} == 'macos-latest' ]]; then
          echo "debugfilename=wretch-debug-nightly-macos" >> $GITHUB_OUTPUT
          echo "releasefilename=wretch-release-nightly-macos" >> $GITHUB_OUTPUT
          mv target/debug/wretch target/debug/wretch-debug-nightly-macos
          mv target/release/wretch target/release/wretch-release-nightly-macos
        else
          echo "debugfilename=wretch-debug-nightly-linux" >> $GITHUB_OUTPUT
          echo "releasefilename=wretch-release-nightly-linux" >> $GITHUB_OUTPUT
          mv target/debug/wretch target/debug/wretch-debug-nightly-linux
          mv target/release/wretch target/release/wretch-release-nightly-linux
        fi

    - name: Upload nightly debug artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.rename.outputs.debugfilename }}
        path: target/debug/${{ steps.rename.outputs.debugfilename }}

    - name: Upload nightly release artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.rename.outputs.releasefilename }}
        path: target/release/${{ steps.rename.outputs.releasefilename }}

  package:
    name: Package Builds
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v4
      with:
        path: "artifacts2"

    - name: move artifacts
      run: |
        mkdir artifacts
        mv artifacts2/*/* artifacts

    - name: Release nightly
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: andelf/nightly-release@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly
        name: 'Development Release'
        body: |
          Generated nightly release for wretch.
          Will be unstable!
        files: |
          artifacts/*
  
